### ISSUE TITLE
program crashed when run long time

### ISSUE THREAD

**Issue by Matrix-Zhang** [dpc/mioco.pre-0.9#158]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', ../src/libcore/result.rs:837
stack backtrace:
   1:     0x558d4d05a55a - std::sys::imp::backtrace::tracing::imp::write::h917062bce4ff48c3
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x558d4d05f5ef - std::panicking::default_hook::{{closure}}::h0bacac31b5ed1870
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x558d4d05d426 - std::panicking::default_hook::h5897799da33ece67
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x558d4d05dad7 - std::panicking::rust_panic_with_hook::h109e116a3a861224
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x558d4d05d964 - std::panicking::begin_panic::hbb38be1379e09df0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x558d4d05d889 - std::panicking::begin_panic_fmt::h26713cea9bce3ab0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x558d4d05d817 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
   8:     0x558d4d09ba5d - core::panicking::panic_fmt::hcfbb59eeb7f27f75
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
   9:     0x558d4cba43a4 - core::result::unwrap_failed::h6578dfa2e8ca0b85
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
  10:     0x558d4cb8cf52 - <core::result::Result<T, E>>::unwrap::h4e7fac09f54e715b
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/result.rs:737
  11:     0x558d4cbdca6d - cs_server::main::{{closure}}::hcdafa5e77469d732
                        at /home/matrix/release/cloud_scale_system/src/server/main.rs:58
  12:     0x558d4cbd209b - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::hb191a629c94355a4
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panic.rs:295
  13:     0x558d4cbd68b1 - mioco::src::coroutine::Coroutine::spawn::{{closure}}::{{closure}}::hf639f7de5db627bb
                        at /home/matrix/.cargo/registry/src/github.com-1ecc6299db9ec823/mioco-0.8.1/src/coroutine.rs:248
  14:     0x558d4cb7fec2 - std::panicking::try::do_call::h0b958e8943ce1bbd
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:356
  15:     0x558d4d0670ca - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  16:     0x558d4cb7f8a7 - std::panicking::try::hefc16b5bc122ab64
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
  17:     0x558d4cb7c56b - std::panic::catch_unwind::h422481fe314204f9
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
  18:     0x558d4cbd9688 - mioco::src::coroutine::Coroutine::spawn::{{closure}}::h4a679703206e4bd4
                        at /home/matrix/.cargo/registry/src/github.com-1ecc6299db9ec823/mioco-0.8.1/src/coroutine.rs:241
  19:     0x558d4cbda5af - <mioco::src::thunk::Thunk<'a, (), R>>::new::{{closure}}::hedf2aabe4aac7399
                        at /home/matrix/.cargo/registry/src/github.com-1ecc6299db9ec823/mioco-0.8.1/src/thunk.rs:20
  20:     0x558d4cbc5ec7 - <F as mioco::src::thunk::Invoke<A, R>>::invoke::hac1374ccf6fe1595
                        at /home/matrix/.cargo/registry/src/github.com-1ecc6299db9ec823/mioco-0.8.1/src/thunk.rs:47
  21:     0x558d4cc03aac - <mioco::src::thunk::Thunk<'a, A, R>>::invoke::hb771f18041dc0a2f
                        at /home/matrix/.cargo/registry/src/github.com-1ecc6299db9ec823/mioco-0.8.1/src/thunk.rs:33
  22:     0x558d4cbfd330 - mioco::src::coroutine::Coroutine::spawn::coroutine_context_start_fn::hc629b34b0224cdf7
                        at /home/matrix/.cargo/registry/src/github.com-1ecc6299db9ec823/mioco-0.8.1/src/coroutine.rs:223
  23:     0x558d4cc1baaa - <unknown>
                        at src/asm/make_x86_64_sysv_elf_gas.S:51

```

**Comment by Matrix-Zhang** [comment]
after cargo update, never crashed
